### ISSUE TITLE
Terragrunt releases < 0.18.1 do not have SHA256SUMS

### ISSUE THREAD

**Issue by jpalomaki** [superblk/terve#5]
Install emits:
```
ERROR: HTTP status client error (404 Not Found) for url (https://github.com/gruntwork-io/terragrunt/releases/download/v0.13.11/SHA256SUMS)
```

**Comment by jpalomaki** [comment]
@brikis98 :wave: Would it possible to retroactively add `SHA256SUMS` release assets for older `terragrunt` releases (I for one would feel better installing w/integrity check, rather than just emitting a warning about skipped checksum check)? On a related note: are there plans to GPG sign terragrunt releases (like terraform does it)?

**Comment by brikis98** [comment]
Possible? Yes. But from a time perspective, I don't think it's something we'll be able to get to any time soon. We do plan to sign all our releases too, but again, time constraints are going to be the issue, and I'm not sure when we'll get to it.

**Comment by jpalomaki** [comment]
> Possible? Yes. But from a time perspective, I don't think it's something we'll be able to get to any time soon. We do plan to sign all our releases too, but again, time constraints are going to be the issue, and I'm not sure when we'll get to it.

Understood. Logging a warning for older releases is then probably the best course of action here. Thanks for the quick reply. :+1:
